apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-argovlad-yaml
spec: 
 project: default
 source:
   repoURL: https://github.com/Vlad-b27/New-folder.git
   targetRevision: main
   path: argo
 destination:
    server: https://kubernetes.default.svc
    namespace: argocd
 syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
    automated:
      selfHeal: true
      prune: true
      
   
    